version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:16"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: "@types/node"
    versions:
    - "> 13.1.1"
    - "< 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
