version: '3.7'
services:
  jaeger:
    hostname: jaeger
    container_name: jaeger
    image: jaegertracing/all-in-one:1.21
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
