version: '3.9'

services:
  zookeeper:
    image: 'debezium/zookeeper:1.3'
    hostname: zookeeper
    container_name: zookeeper
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'

  kafka:
    image: calcifer-kafka
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-kafka
    command: sh -c "sh /bin/init-kafka.sh"
    hostname: kafka
    container_name: kafka
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - 'KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9091,PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
    depends_on:
      - zookeeper

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: calcifer
      POSTGRES_PASSWORD: 5b;sgkF,)S:fA;3\
      POSTGRES_USER: calcifer
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
